# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
"""Signal 5: cross-evidence review.

Sends the original photo together with the ELA heatmap and FFT spectrum to the
multimodal model in one Converse call, so it reads the forensic artefacts in context.
A bright ELA region along a fabric seam is ordinary texture; a bright rectangle in the
middle of a flat surface is not. This is a second opinion on the deterministic signals,
not a replacement for them.
"""
import json
import os

import boto3

MODEL_ID = os.environ["BEDROCK_MODEL_ID"]
IMAGE_BUCKET = os.environ["IMAGE_BUCKET"]

_s3 = boto3.client("s3")
_bedrock = boto3.client("bedrock-runtime")

PROMPT = """You are a forensic image analyst reviewing evidence produced by an image integrity pipeline.

You have been given up to three images, in this order:

1. The submitted photo.

2. If present, an Error Level Analysis heatmap of that photo, generated by this pipeline.
   The heatmap is rendered as the original photo blended with a colour overlay, so it always
   looks like a blue-tinted copy of the photo. That tint is the rendering, not a finding.
   Read it as follows. Mostly blue means uniform recompression error, which is normal.
   Scattered red along genuine texture edges such as hair, fabric seams, and high-contrast
   boundaries is also normal. The one suspicious pattern is a contiguous, sharply bounded
   bright region that does not correspond to a texture edge in the photo, which indicates
   pasted or edited content.

3. If present, a log power spectrum of the photo, also generated by this pipeline, rendered
   in grayscale. A bright centre with a smooth radial fade, and a cross through the centre,
   is normal for any photograph; the cross comes from the image borders. The suspicious
   patterns are a grid of periodic spikes away from the axes, or a high-frequency field that
   stays bright instead of decaying.

The heatmap and spectrum are diagnostic renderings from this pipeline, not submissions. Judge
only whether the photo itself shows manipulation, using the artefacts as evidence. Do not
remark that the artefacts look processed.

Respond with JSON only, matching this schema:
{"verdict": "pass" | "flag", "confidence": 0.0-1.0, "rationale": "<2-3 sentences citing what you saw in the artefacts and where in the frame>"}"""


def _image_block(key):
    obj = _s3.get_object(Bucket=IMAGE_BUCKET, Key=key)
    fmt = "png" if key.lower().endswith(".png") else "jpeg"
    return {"image": {"format": fmt, "source": {"bytes": obj["Body"].read()}}}


def lambda_handler(event, _context):
    key = event["imageKey"]
    prior = event.get("signals", [])

    content = [_image_block(key)]
    labels = ["photo"]
    for s in prior:
        if s.get("artifactKey"):
            content.append(_image_block(s["artifactKey"]))
            labels.append(s["signal"])

    content.append({"text": PROMPT + f"\n\nImages provided, in order: {', '.join(labels)}."})

    response = _bedrock.converse(
        modelId=MODEL_ID,
        messages=[{"role": "user", "content": content}],
        inferenceConfig={"maxTokens": 500},
    )

    text = response["output"]["message"]["content"][0]["text"]
    try:
        start, end = text.index("{"), text.rindex("}") + 1
        result = json.loads(text[start:end])
        verdict = result.get("verdict", "flag")
        # Clamp to the range the schema asks for; see the matching note in the semantic
        # signal. This handler reads the submitted photo too, so it is injectable by the
        # same image, and an out-of-range confidence would produce a negative score.
        confidence = min(max(float(result.get("confidence", 0.5)), 0.0), 1.0)
        rationale = str(result.get("rationale", ""))[:1000]
    except (ValueError, KeyError):
        verdict, confidence, rationale = "flag", 0.3, "Model response could not be parsed; flagged for manual review."

    return {
        "signal": "cross_evidence",
        "verdict": verdict,
        "score": confidence if verdict == "flag" else 1 - confidence,
        "rationale": rationale,
    }
